###
# добавление продуктов в корзину с указанием их количества
POST localhost:8081/cart/2/product/2
Content-Type: application/json

{
"amount": 9
}

###
# изменение количества продукта в корзине
PUT localhost:8081/cart/2/product/2
Content-Type: application/json

{
  "amount": 1
}

###
# удаление продукта из корзины
DELETE localhost:8081/cart/2/product/2
