###
# регистрация клиента
POST localhost:8081/clients
Content-Type: application/json

{
  "login": "asd",
  "password": "q1w2e3",
  "email": "123@yandex.ru"
}

###
# получение клиента
GET localhost:8081/clients/2

###
# удаление клиента
DELETE localhost:8081/clients/1

###
# создание продукта
POST localhost:8081/products
Content-Type: application/json

{
  "name": "Форель",
  "price": 100,
  "amount": 10
}

###
# изменение продукта
PUT localhost:8081/products
Content-Type: application/json

{
  "id": 1,
  "name": "Форель",
  "price": 150,
  "amount": 10
}

###
# удаление продукта
DELETE localhost:8081/products/1

###
# получение отдельного продукта
GET localhost:8081/products/1

###
# получение списка продуктов c возможностью фильтрации по наименованию (-)
GET localhost:8081/product?name=Креветки

###
# добавление продукта в корзину
POST localhost:8081/cart/1/product/1
Content-Type: application/json

# изменение количества продукта в корзине
###
PUT localhost:8081/cart/1/product/1
Content-Type: application/json

{
  "amount": 100
}

###
# удаление продукта из корзины
DELETE localhost:8081/cart/1/product/1


###
# оплата
POST localhost:8081/payment
Content-Type: application/json

{
  "cardNumber": 800,
  "userId": 1
}